# ==========================================================
# 1. 다국어 설정 (최종 완성 버전)
# ==========================================================
defaultContentLanguage = 'ko'

[languages]
  [languages.ko]
    languageName = '한국어'
    weight = 1
    title = 'Archive 03'
    [languages.ko.outputs]
      home = ["HTML", "JSON", "RSS"]
      section = ["HTML", "RSS"]
    [languages.ko.params]
      subtitle = '세 명의 인외 소녀가 전하는 투자 인사이트'
      dateFormat = "2006년 1월 2일"
    [[languages.ko.menu.main]]
      identifier = "article"
      name = "HOME"
      url = "/"
      weight = 10
    [[languages.ko.menu.main]]
      identifier = "about"
      name = "ABOUT"
      pageRef = "/about.ko.md"
      weight = 20

  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'Archive 03'
    [languages.en.outputs]
      home = ["HTML", "JSON", "RSS"]
      section = ["HTML", "RSS"]
    [languages.en.params]
      subtitle = 'Financial Insights from 3 Non-human Girls'
      dateFormat = "January 2, 2006"
    [[languages.en.menu.main]]
      identifier = "article"
      name = "HOME"
      url = "/en/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "about"
      name = "ABOUT"
      pageRef = "/about.en.md"
      weight = 20

# ==========================================================
# 2. URL 구조 설정
# ==========================================================
[permalinks]
  reports = '/:year/:month/:slug/'

# ==========================================================
# 3. 기존 설정 (일부 삭제됨)
# ==========================================================
languageCode = 'ko-KR'
timeZone = "Asia/Seoul"

[pagination]
  pagerSize = 5

[params]
  author = '야차완'
  description = "Archive 03은 세 명의 인외(人外) 소녀가 최신 데이터를 바탕으로 투자에 대한 인사이트를 전하는 연재형 블로그입니다."
  favicon = "/favicon.ico"
  
  [params.giscus]
    repo = "heavyrain39/archive03"
    repoId = "R_kgDOO7KqJQ"
    category = "General"
    categoryId = "DIC_kwDOO7KqJc4CrlEO"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "0"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "dark_dimmed" 
    loading = "lazy"

# Goldmark 설정
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

# 미디어 타입 및 출력 포맷 설정
[mediaTypes]
  [mediaTypes."text/css"]
    suffixes = ["css"]

[outputFormats.JSON]
  baseName = "index"
  isPlainText = true
  mediaType = "application/json"